### ISSUE TITLE
Regarding Learning Rate

### ISSUE THREAD

**Issue by kailasdayanandan** [ZFTurbo/2nd-place-solution-for-VinBigData-Chest-X-ray-Abnormalities-Detection#8]
Regarding ivan part on mmdetection Can you please upload schedule_1x.py.
The below error is seen. There was another solution recommended in (https://github.com/open-mmlab/mmdetection/issues/6456)
Can you confirm on the same.

Traceback (most recent call last):
  File "/home/prashant/anaconda3/envs/kmmdet/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/prashant/anaconda3/envs/kmmdet/lib/python3.7/site-packages/mmcv/runner/hooks/lr_updater.py", line 264, in __init__
    super(CosineAnnealingLrUpdaterHook, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'step'

**Comment by kailasdayanandan** [comment]
Can you check this too..

https://github.com/open-mmlab/mmdetection/issues/6456
